# Copy this file in your project in a folder "config/" at the root
# then uncomments things you want to use for the scripts, you can add elements to array

# Project settings
project:
  # directory: "force-app/main/default/"
  github_repository_url: "https://github.com/BoboJD/Salesforce-Tools"
  # archive_logs_folder: "\\\\NAS\\Archive\\Log__c"

# Org settings
org_settings:
  production_org_id: "00D24000000q9b8EAA"
  devhub_name: "salesforce-tools"
  # territories_used: true
  # experience_cloud_used: true
  # org_shape_enable: true
  # profile_used: true
  # packages:
  #   - "Salesforce Tools"

# Test settings
test_settings:
  min_coverage: 90
  # ignore_selectors: true

# Translation to remove
translation_settings:
  # sobjects:
  #   Account:
  #     layouts:
  #       - "ELLI Account layout"
  #     quickActions:
  #       - "ESCONNECT__"
  untracked:
    - "customApplications"
    - "quickActions"
    - "reportTypes"
  # globalQuickActions:
  #   - "SearchEngineGlobalActions"

# Data backup
# data_backup:
#  - "SELECT Id, Name, FIELDS(CUSTOM) FROM APXTConga4__Conga_Merge_Query__c ORDER BY Name LIMIT 200"

# Auto update settings for scripts
# features:
#   auto_update_settings:
#     check_windows_git_update: true
#     check_global_npm_packages_update: true
#     check_npm_packages_update: true
#   always_retrieve_development: true

# Picklists with controlling field deploy issues
# controlling_picklists_with_deploy_issue:
#   - "Opportunity.SObjectFieldApiName__c"

# Standard metadata to rename
# standard_metadata_to_rename:
#   - "RecordType:Account.Business_Account:Account.B2B"
#   - "PicklistValue:Account.Type.Partner:Account.Type.Partenaire"

# Rights to remove in profiles
# profile_settings:
#   user_permissions_to_delete:
#     - "TraceXdsQueries"
#     - "AllowObjectDetectionTraining"
#   unnecessary_permissions_to_delete:
#     - "customMetadataTypeAccesses"
#     - "fieldPermissions"
#     - "recordTypeVisibilities"